### ISSUE TITLE
Nav Bar

### ISSUE THREAD

**Issue by bradley-doyle** [marissagodwin/portfolio#4]
On full screen desktop for safari your nav is all the way up in the to left of the screen but all the content is in the middle and a bit further down from the top. (see photo)

<img width="942" alt="screen shot 2015-10-06 at 4 41 31 pm" src="https://cloud.githubusercontent.com/assets/4565418/10321883/23c52352-6c49-11e5-81de-19f99b678b59.png">

it gets further the bigger the screen.

**Comment by marissagodwin** [comment]
Thanks, fit it into my grid. Keeping it left aligned though :)
